### ISSUE TITLE
Keep attention to your secrets.

### ISSUE THREAD

**Issue by Zikoel** [andreafalzetti/node-fatturazione-elettronica-aruba#2]
You have push your email and secret publicly. Anyone with this information can deploy the what it want under  your name. I suggest to remove this information and put directly inside the correct section on travis.

**Comment by andreafalzetti** [comment]
Hi @Zikoel, the token is encrypted at rest using Travis's public key. They don't give you the private key so even myself cannot decrypt it, so I don't understand how that can be a risk. If you have more information, please let me know.

**Comment by Zikoel** [comment]
You are right! I have completely misunderstood the travis field. Sorry, and thank you for the lib!
