### ISSUE TITLE
Download fatture in XML

### ISSUE THREAD

**Issue by BigNerd95** [andreafalzetti/node-fatturazione-elettronica-aruba#25]
Le API permettono di scaricare anche le fatture in XML?
Ho controllato sulla documentazione aruba e non sembra possibile.
Me lo potete confermare?

**Comment by andreafalzetti** [comment]
Le API ritornano le fatture in formato base64. Nel progetto dove uso questa libreria facciamo l'upload su S3 e a quel punto e' possibile scaricare la fattura tramite un URL.
