### ISSUE TITLE
login "demo"

### ISSUE THREAD

**Issue by jampy** [andreafalzetti/node-fatturazione-elettronica-aruba#34]
I can sign in to the Aruba account with `{env: "prod"}`. However, the login data is not accepted if I use `{env: "demo"}` . 

I get the following response when trying to sign in to "demo":

```javascript
{ success: false,
  error: 'invalid_grant',
  error_description: 'The user name or password is incorrect.' }
```

Where do I get my demo login credentials? The [Aruba documentation](https://fatturazioneelettronica.aruba.it/apidoc/docs.html#overview-enviroments) was no help for me and also my personal "fatturazione elettronica" portal does not mention the API at all.

I want to test the API before sending real invoices...

Thanks.

**Comment by andreafalzetti** [comment]
Hei @jampy, you have to request demo credentials to Aruba, your prod credentials will not work.

**Comment by jampy** [comment]
Sorry to ask *you*, but what's the best way to get these credentials? I tried to click on `Assistenza` from the *fattura elettronica* dashboard and it leads me to https://assistenza.aruba.it/it but my login is not accepted there...

**Comment by andreafalzetti** [comment]
@jampy I will ask my colleague who has requested them and I'll let you know!

**Comment by andreafalzetti** [comment]
@jampy we requested them by phone 💀 

I have a contact number that I can share you privately, but more importantly I can share with you temporary credentials until you get yours. The Aruba demo environment credentials that they sent us apparently are *already* used by other people, in fact, when you login to their dashboard or fetch the invoices by API, you will see a lot of data with different VATs numbers for this reason. If you are happy with that, or simply want the phone number and name, drop me a DM somewhere.

**Comment by jampy** [comment]
> drop me a DM somewhere.

Your link leads to your Twitter account. I am not allowed to send you direct messages there, so I wrote [a tweet](https://twitter.com/jampy81/status/1105815350086692867).
