### ISSUE TITLE
Aruba "premium" account required?

### ISSUE THREAD

**Issue by jampy** [andreafalzetti/node-fatturazione-elettronica-aruba#40]
Aruba (with `{env:"prod"}`) declines my invoices with error `0093 - Errore deleghe utente`. However, the same file is accepted **and sent successfully to SDI** when uploaded via the normal website. 

Is the web service restricted to the (very expensive) [premium accounts](https://www.pec.it/fatturazione-elettronica/soluzioni-business-per-imprese.aspx) perhaps?

**Comment by andreafalzetti** [comment]
For errors related to Aruba please get in touch with them. For what I can say, we have an account that sends invoices on behalf of our customers so we have to have the "delega" which is set up via the Aruba control panel for each client.

**Comment by jampy** [comment]
Unfortunately, it's confirmed... :-(

>in merito alla Sua richiesta siamo ad informarla che **il servizio di Fatturazione elettronica account base da Lei acquistato, non prevede la possibilità di inviare fatture tramite web service**.
> Tale funzione può essere attivata solo collegando il suo pannello, tramite delega, ad un **account Premium**.
